[package]
name = "proc-macro-attr-like"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test_attr_macroinner = { path = "test_attr_macroinner" }
