[package]
name = "parity-tokio-ipc-s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-tokio-ipc = "0.9.0"
tokio = { version = "1.7.0", features = ["full"] }
futures = "0.3"