[package]
name = "sftp-learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = {version = "0.9",features=["vendored-openssl"]}
retry = "2.0.0"