[package]
name = "rust"
version = "0.2.0"
authors = ["Nick Alexander <nalexander@mozilla.com>"]

[dependencies]
jni = "0.5.2"

[lib]
crate_type = ["staticlib", "dylib"]

[features]
default = ["foo"]
foo = []
bar = []

