[package]
name = "decorator-learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
macros = { path = "./macros" }
adorn = "0.4.0"
retry = "2.0.0"